// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkAPI.Models;

namespace ParkAPI.Migrations
{
    [DbContext(typeof(ParkAPIContext))]
    partial class ParkAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Beach");

                    b.Property<int>("EntranceFee");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("ParkingPermit");

                    b.Property<bool>("PicnicArea");

                    b.Property<bool>("Playground");

                    b.Property<bool>("RealBathrooms");

                    b.Property<string>("Type");

                    b.Property<bool>("VisitorCenter");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("ParkAPI.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Accessible");

                    b.Property<int>("Clean");

                    b.Property<string>("Comments");

                    b.Property<int>("FunForKids");

                    b.Property<int>("FunForParents");

                    b.Property<int>("ParkId");

                    b.Property<int>("UserId");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ParkAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
